# Generated by Django 5.1.7 on 2025-07-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("internship_role", models.CharField(max_length=255)),
                (
                    "internship_type",
                    models.CharField(
                        choices=[
                            ("in_office", "In-Office"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "internship_field",
                    models.CharField(
                        choices=[
                            ("accounts", "Accounts"),
                            ("administration", "Administration"),
                            ("chemical", "Chemical"),
                            ("technology", "Technology"),
                            ("finance", "Finance"),
                            ("banking", "Banking"),
                            ("healthcare", "Healthcare"),
                            ("human_resource", "Human Resource"),
                            ("education", "Education"),
                            ("engineering", "Engineering"),
                            ("retail", "Retail"),
                            ("marketing", "Marketing"),
                            ("hospitality", "Hospitality"),
                            ("consulting", "Consulting"),
                            ("manufacturing", "Manufacturing"),
                            ("media", "Media"),
                            ("transportation", "Transportation"),
                            ("telecommunications", "Telecommunications"),
                            ("nonprofit", "Nonprofit"),
                            ("activate_windows", "Activate Windows"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "internship_nature",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("internship_description", models.TextField()),
                ("required_skills", models.CharField(max_length=255)),
                ("duration_months", models.PositiveIntegerField()),
                ("application_start_date", models.DateField()),
                ("application_end_date", models.DateField()),
                ("stipend", models.CharField(max_length=50)),
                ("eligibility_criteria", models.TextField()),
                ("degrees_preferred", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_mobile_number", models.CharField(max_length=15)),
                ("company_information", models.TextField()),
                ("internship_responsibilities", models.TextField()),
                ("total_vacancies", models.PositiveIntegerField(default=1)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
