# Generated by Django 5.1.7 on 2025-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0003_alter_facetofaceinterview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
