# Generated by Django 5.1.7 on 2025-08-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0004_internship_modified_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaceToFaceInterview",
        ),
    ]
