# Generated by Django 5.1.7 on 2025-08-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Interview_Questions", "0003_remove_quiz_percentage_for_qualified"),
        ("internships", "0005_delete_facetofaceinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="pass_percentage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="quiz_open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="quiz_open_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="quiz_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizSets",
                to="Interview_Questions.quiz",
            ),
        ),
    ]
