# Generated by Django 5.1.7 on 2025-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_internshipapplication_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internshipapplication",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="internshipapplication",
            name="email",
        ),
        migrations.RemoveField(
            model_name="internshipapplication",
            name="name",
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="application_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="application_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="company_information",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="contact_mobile_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="degrees_preferred",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="district",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="duration_months",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="eligibility_criteria",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="internship_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="internship_field",
            field=models.CharField(
                choices=[
                    ("accounts", "Accounts"),
                    ("administration", "Administration"),
                    ("chemical", "Chemical"),
                    ("technology", "Technology"),
                    ("finance", "Finance"),
                    ("banking", "Banking"),
                    ("healthcare", "Healthcare"),
                    ("human_resource", "Human Resource"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("retail", "Retail"),
                    ("marketing", "Marketing"),
                    ("hospitality", "Hospitality"),
                    ("consulting", "Consulting"),
                    ("manufacturing", "Manufacturing"),
                    ("media", "Media"),
                    ("transportation", "Transportation"),
                    ("telecommunications", "Telecommunications"),
                    ("nonprofit", "Nonprofit"),
                    ("activate_windows", "Activate Windows"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="internship_nature",
            field=models.CharField(
                choices=[("full_time", "Full Time"), ("part_time", "Part Time")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="internship_responsibilities",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="internship_type",
            field=models.CharField(
                choices=[
                    ("in_office", "In-Office"),
                    ("hybrid", "Hybrid"),
                    ("remote", "Remote"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="required_skills",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="stipend",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="total_vacancies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="internshipapplication",
            name="internship_role",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
