# Generated by Django 5.1.7 on 2025-08-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_remove_internshipapplication_contact_number_and_more"),
        ("internships", "0004_internship_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="internship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="internships.internship",
            ),
        ),
    ]
