# Generated by Django 5.1.7 on 2025-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_internshipapplication_internship"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
