# Generated by Django 5.1.7 on 2025-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0005_internshipapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="candidate_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="candidate_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="candidate_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
