# Generated by Django 5.1.7 on 2025-08-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_internshipapplication_candidate_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceToFaceInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("internship_role", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("zoom", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidates.internshipapplication",
                    ),
                ),
            ],
        ),
    ]
