# Generated by Django 5.1.7 on 2025-08-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_facetofaceinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetofaceinterview",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
