# Generated by Django 5.1.7 on 2025-08-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0008_facetofaceinterview_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaceToFaceInterview",
        ),
    ]
