# Generated by Django 5.1.7 on 2025-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_delete_facetofaceinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="test_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="test_passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="test_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
