# Generated by Django 5.1.7 on 2025-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Interview_Questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="percentage_for_qualified",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
