# Generated by Django 5.1.7 on 2025-08-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Interview_Questions", "0002_alter_quiz_percentage_for_qualified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="percentage_for_qualified",
        ),
    ]
