# Generated by Django 5.1.7 on 2025-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("interviewer", "Interviewer"),
                    ("candidate", "Candidate"),
                ],
                max_length=50,
            ),
        ),
    ]
