# Generated by Django 5.1.7 on 2025-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("employee", "Employee"),
                    ("candidate", "Candidate"),
                ],
                max_length=10,
            ),
        ),
    ]
